deploy:
  device: gaudi
  version: 1.2.0
  modelUseHostPath: /mnt/models
  HUGGINGFACEHUB_API_TOKEN: ''
  node:
    - 1
    - 2
    - 4
    - 8
  namespace: ''
  timeout: 1000
  interval: 5
  services:
    backend:
      resources:
        enabled: false
        cores_per_instance: '16'
        memory_capacity: 8000Mi
      replicaCount:
        - 1
        - 2
        - 4
        - 8
    teirerank:
      enabled: true
      model_id: ''
      resources:
        enabled: false
        cards_per_instance: 1
      replicaCount:
        - 1
        - 1
        - 1
        - 1
    tei:
      model_id: ''
      resources:
        enabled: false
        cores_per_instance: '80'
        memory_capacity: 20000Mi
      replicaCount:
        - 1
        - 2
        - 4
        - 8
    llm:
      engine: vllm
      model_id: meta-llama/Meta-Llama-3-8B-Instruct
      replicaCount:
        with_teirerank:
          - 7
          - 15
          - 31
          - 63
        without_teirerank:
          - 8
          - 16
          - 32
          - 64
      resources:
        enabled: false
        cards_per_instance: 1
      model_params:
        vllm:
          batch_params:
            enabled: true
            max_num_seqs:
              - 1
              - 2
              - 4
              - 8
          token_params:
            enabled: false
            max_input_length: ''
            max_total_tokens: ''
            max_batch_total_tokens: ''
            max_batch_prefill_tokens: ''
        tgi:
          batch_params:
            enabled: true
            max_batch_size:
              - 1
              - 2
              - 4
              - 8
          token_params:
            enabled: false
            max_input_length: '1280'
            max_total_tokens: '2048'
            max_batch_total_tokens: '65536'
            max_batch_prefill_tokens: '4096'
    data-prep:
      resources:
        enabled: false
        cores_per_instance: ''
        memory_capacity: ''
      replicaCount:
        - 1
        - 1
        - 1
        - 1
    retriever-usvc:
      resources:
        enabled: false
        cores_per_instance: '8'
        memory_capacity: 8000Mi
      replicaCount:
        - 1
        - 2
        - 4
        - 8
    redis-vector-db:
      resources:
        enabled: false
        cores_per_instance: ''
        memory_capacity: ''
      replicaCount:
        - 1
        - 1
        - 1
        - 1
    chatqna-ui:
      replicaCount:
        - 1
        - 1
        - 1
        - 1
    nginx:
      replicaCount:
        - 1
        - 1
        - 1
        - 1
benchmark:
  user_queries:
    - 640
  concurrency:
    - 128
  load_shape_type: constant
  poisson_arrival_rate: 1
  warmup_iterations: 10
  seed: 1024
  bench_target:
    - chatqnafixed
    - chatqna_qlist_pubmed
  dataset:
    - /home/sdp/upload_file.txt
    - /home/sdp/pubmed_10000.txt
  prompt:
    - 10
    - 1000
  llm:
    max_token_size:
      - 128
      - 256
