name: Deploy and Benchmark on Gaudi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies (if needed)
        run: |
          pip install -r requirements.txt || echo "No dependencies to install"

      - name: Deploy to Gaudi
        run: |
          chmod +x deploy.sh
          ./deploy.sh

      - name: Wait for Services to be Ready
        run: |
          sleep 100  # Adjust based on service readiness

  benchmark:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Benchmark Tests
        run: |
          chmod +x benchmark.sh
          ./benchmark.sh

      - name: Upload Benchmark Logs
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-logs
          path: logs/
