name: Benchmark Test for ChatQnA
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  validate-config:
    name: Validate YAML Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install YAML Linter
        run: pip install yamllint
      - name: Validate YAML Syntax
        run: yamllint benchmark_chatqna.yaml
  test-benchmark:
    name: Benchmark Gaudi Deployment
    runs-on: ubuntu-latest
    needs: validate-config
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install -r requirements.txt || echo "No requirements.txt found"
      - name: 'Run Core Count, Memory Speed, Model Change Tests'
        env:
          HUGGINGFACEHUB_API_TOKEN: '${{ secrets.HUGGINGFACEHUB_API_TOKEN }}'
        run: |
          python test.py
